version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: db
    environment: 
      - POSTGRES_DB=my_store
      - POSTGRES_USER=daniel
      - POSTGRES_PASSWORD=No2vale3
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=daniel@mail.com
      - PGADMIN_DEFAULT_PASSWORD=No2vale3
    ports:
      - 5050:80
